product/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'products', ProductView)

app_name = 'products'
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('new/', AddProductView.as_view(), name='new_product'),
    path('list_product', list_product, name='list_product'),
    path('list_product/wallpaper/', list_product_wallpaper, name='list_product_wallpaper'),
    path('list_product/artifact/', list_product_artifact, name='list_product_artifact'),
    path('search/', search, name='filter_product'),
    path('index/', index, name='youtube_search'),
    path('<pk>/', product_detail, name='product_detail'),
]


# list of namespace urls for templates:
#     products:new_product
#     products:product_list
#     products:detailed_product

product_catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('product.urls')),
    path('', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
PRODUCT_TYPES = [
    ('Wallpaper', 'Wallpaper'),
    ('Artifact', 'Artifact'),
]

class Product(models.Model):
    title = models.CharField(max_length=200, null=False)
    type = models.CharField(max_length=9, choices=PRODUCT_TYPES, null=False)
    image = models.ImageField(blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, auto_created=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:list_product')

product/views.py
import requests
from isodate import parse_duration
from product.serializers import ProductSerializer

from .filters import *
from .models import Product

from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, DetailView
from django.core.paginator import Paginator
from django.conf import settings
from rest_framework import viewsets, permissions
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework.generics import ListAPIView, CreateAPIView, DestroyAPIView, UpdateAPIView
# Create your views here.
# class ProductDetail(DetailView):
#     model = Product
#     template_name = 'product/product_detail.html'


# View for YouTube videos:
def index(request):
    videos = []
    if request.method == 'POST':
        search_url = 'https://www.googleapis.com/youtube/v3/search'
        video_url = 'https://www.googleapis.com/youtube/v3/videos'
        search_params = {
            'part': 'snippet',
            'q': request.POST['search'],
            'key': settings.YOUTUBE_DATA_API_KEY,
            'maxResults': 9,
            'type': 'video'
        }

        r = requests.get(search_url, params=search_params)
        results = r.json()['items']
        video_ids = []
        for result in results:
            video_ids.append(result['id']['videoId'])
        if request.POST['submit'] == 'lucky':
            return redirect(f'https://www.youtube.com/watch?v={video_ids[0]}')
        video_params = {
            'key': settings.YOUTUBE_DATA_API_KEY,
            'part': 'snippet,contentDetails',
            'id': ','.join(video_ids),
            'maxResults': 12
        }

        r = requests.get(video_url, params=video_params)
        results = r.json()['items']
        for result in results:
            video_data = {
                'title': result['snippet']['title'],
                'id': result['id'],
                'url': f'https://www.youtube.com/watch?v={result["id"]}',
                'duration': int(parse_duration(result['contentDetails']['duration']).total_seconds() // 60),
                'thumbnail': result['snippet']['thumbnails']['high']['url']
            }

            videos.append(video_data)
    context = {
        'videos': videos
    }
    return render(request, 'product/youtube.html', context)


def product_detail(request, pk):
    context = {}
    context["data"] = Product.objects.get(id=pk)
    return render(request, 'product/product_detail.html', context)


class AddProductView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = 'product/add_product.html'
    fields = ['title', 'type', 'image', 'description']

def list_product(request):
    query_product = Product.objects.all()
    product = Product.objects.all()
    paginator = Paginator(product, 3)
    # The page query string value is fetched with the request.GET.get() function and passed to the paginator.get_page()
    page = request.GET.get('page')
    product = paginator.get_page(page)
    filter = ProductFilter(request.GET, queryset=query_product)
    return render(request, 'product/list_product.html', {'product': product, 'filter': filter})


def list_product_wallpaper(request):
    product = Product.objects.filter(type="Wallpaper")
    filter = ProductFilter(request.GET, queryset=product)
    return render(request, 'product/list_product.html', {'filter': filter})


def list_product_artifact(request):
    product = Product.objects.filter(type="Artifact")
    filter = ProductFilter(request.GET, queryset=product)
    return render(request, 'product/list_product.html', {'filter': filter})


def search(request):
    objects = Product.objects.all()
    filter = ProductFilter(request.GET, queryset=objects)
    return render(request, 'product/list_product.html', {'filter': filter})


class ProductView(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [permissions.IsAuthenticated]

# class ListProductsView(LoginRequiredMixin, ListView):
#     model = Product
#     template_name = 'product/list_product.html'
#     paginate_by = 2

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>{% block title %}Product catalog{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</head>
{% block content %}
{% endblock %}
</html>

templates/nav_bar.html
{% load static %}
{% block content %}
    <br>
    <a data-role="button" href="{% url 'products:list_product' %}">
        <img src="{% static "img/mb-logo-grey.png" %}" alt="" height="34"
             class="d-inline-block align-text-top col px-md-3">
    </a>
        <section class="d-lg-flex align-items-end align-content-end justify-content-lg-end contact-clean">
        <a class="btn px-md-3 btn-dark" data-role="button" href="{% url 'logout' %}">Logout</a>
    </section>
    </div><br>
{% endblock %}

templates/product/add_product.html
{% extends 'base.html' %}
{% block content %}
    {% include 'nav_bar.html' %}
    <div class="container">
        <h4>New product</h4><br>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row upload">
            <label class="col-sm-2 form-label">Title</label>
            <div class="mb-3 col-sm-8">
                <input type="text" class="form-control" name="title" placeholder="Title">
            </div>
        </div>
        <br>
        <div class="form-group row upload">
            <label for="description" class="col-sm-2 form-label">Description</label>
            <div class="col-sm-8">
                {#                <input type="text" class="form-control" name="{{ form.description.name }}" placeholder="Description">#}
                <textarea class="form-control" name="description" placeholder="Message" rows="5"></textarea>
            </div>
        </div>
        <br>
        <div class="col-sm-12">
            <label for="Product" class="col-sm-2">Product</label>
            <select name="{{ form.type.name }}" id="{{ form.type.id_for_label }}"
                    class="d-inline-flex p-2 col-sm-4 mx-auto">
                <option value="Artifact">Artifact</option>
                <option value="Wallpaper">Wallpaper</option>
            </select>
        </div>
        <br>
        <div class="form-group">
            <label class="form-label">File input</label>
            <input type="file" class="form-control-file" name="image">
        </div>
        <br>
        <br>
        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary" value="save">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/product/filtered_page.html
{% extends 'base.html' %}

{% block content %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for user in filter.qs %}
    <li>{{ user.title }} - {{ user.description }}</li>
  {% endfor %}
  </ul>
{% endblock %}

templates/product/list_product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% include 'nav_bar.html' %}
     <form method="get">
     <a href="{% url 'products:list_product_wallpaper' %}">Wallpaper</a><br>
    <a href="{% url 'products:list_product_artifact' %}">Artifact</a>
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form><br>
    <a class="btn px-md-3 btn-dark" data-role="button" href="{% url 'products:new_product' %}">Add new product</a><br>
    &nbsp;&nbsp;<br>
{#    <div class="form-check">#}
{#  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" value="{% url 'products:list_product_wallpaper' %}">#}
{#  <label class="form-check-label" for="flexRadioDefault1">#}
{#    Wallpaper list#}
{#  </label>#}
{#</div>#}
{#<div class="form-check">#}
{#  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>#}
{#  <label class="form-check-label" for="flexRadioDefault2">#}
{#    Artifact list#}
{#  </label>#}
{#</div>#}
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Product_id</th>
            <th scope="col">Title</th>
            <th scope="col">Product</th>
            <th scope="col">Image</th>
            {#            <th scope="col">Detail</th>#}
        </tr>
        </thead>
        <tbody>
        {% for product in filter.qs %}
            <tr>
                <th scope="row">{{ product.id }}</th>
                <td><a href="{% url 'products:product_detail' pk=product.id %}">{{ product.title }}</a></td>
                <td>{{ product.type }}</td>
                {#      <td><a href="{{ product.image.url }}">{{ product.image }}</a></td>#}
                <td><img src="{{ product.image.url }}" width="100" height="100"/></td>
                {#                <td></td>   #}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if product.paginator.num_pages > 1 %}
        {% if product.has_previous %}
        <a href="?page={{ product.previous_page_number }}">Previous</a>
        {% endif %}
        <span>Page {{ product.number }} of {{ product.paginator.num_pages }}</span>
        {% if product.has_next %}
        <a href="?page={{ product.next_page_number }}">next</a>
        {% endif %}
    {% endif %}
    <!--    </html>-->
{% endblock %}

templates/product/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .tab-content img {
            width: 100%;
            -webkit-animation-name: opacity;
            animation-name: opacity;
            -webkit-animation-duration: .3s;
            animation-duration: .3s;
        }
        .card {
            margin-top: 50px;
            background: #eee;
            padding: 3em;
            line-height: 1.5em;
        }
        .product-title, .price, .sizes, .colors {
            text-transform: UPPERCASE;
            font-weight: bold;
        }
    </style>
    <body>
{% include 'nav_bar.html' %}

    <div class="container">
        <div class="card">
            <div class="container-fliud">
                <div class="wrapper row">
                    <div class="preview col-md-6">

                        <div class="preview-pic tab-content">
                            <div class="tab-pane active" id="pic-1"><img src="{{ data.image.url }}" height="550"
                                                                         widht="200"/></div>
                        </div>
                    </div>
                    <div class="details col-md-6">
                        <h3 class="product-title">{{ data.title }}</h3>
                        <p class="product-description">{{ data.description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
{% endblock %}





{#When the data is passed as context, it must be mapped with the keyword data in jinja variables#}

templates/product/youtube.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Search YouTube</title>
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'search/album.css' %}" rel="stylesheet">
  </head>
  <body>

{#<main role="main">#}

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Search YouTube</h1>
      <form method="POST">
      <div class="input-group mb-3">
          {% csrf_token %}
          <input type="text" name="search" class="form-control" aria-label="Username">
      </div>
      <p>
        <button type="submit" name="submit" value="search" class="btn btn-primary my-2">YouTube Search</button>
      </p>
      </form>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for video in videos %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ video.thumbnail }}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"></img>
            <div class="card-body">
              <p class="card-text">{{ video.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a type="button" href="{{ video.url }}" class="btn btn-sm btn-outline-secondary">View</a>
                </div>
                <small class="text-muted">{{ video.duration }} mins</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{#</main>#}
</body>
</html>